import type { NextPage } from "next";
import Head from "next/head";
import { Button, ButtonColor } from "../components/Button/Button";
import { Card } from "../components/Card/Card";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card size="sm">
        <span>Holas</span>
      </Card>
    </div>
  );
};

export default Home;
